// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Contactbook.proto
// Protobuf Java Version: 4.29.0

package utils.protobuf;

public final class ContactBookProto {
  private ContactBookProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 0,
      /* suffix= */ "",
      ContactBookProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ContactOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Contact)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string phoneNumber = 2;</code>
     * @return The phoneNumber.
     */
    java.lang.String getPhoneNumber();
    /**
     * <code>string phoneNumber = 2;</code>
     * @return The bytes for phoneNumber.
     */
    com.google.protobuf.ByteString
        getPhoneNumberBytes();

    /**
     * <code>string email = 3;</code>
     * @return The email.
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 3;</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();
  }
  /**
   * Protobuf type {@code Contact}
   */
  public static final class Contact extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Contact)
      ContactOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 0,
        /* suffix= */ "",
        Contact.class.getName());
    }
    // Use Contact.newBuilder() to construct.
    private Contact(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Contact() {
      name_ = "";
      phoneNumber_ = "";
      email_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return utils.protobuf.ContactBookProto.internal_static_Contact_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return utils.protobuf.ContactBookProto.internal_static_Contact_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              utils.protobuf.ContactBookProto.Contact.class, utils.protobuf.ContactBookProto.Contact.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHONENUMBER_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object phoneNumber_ = "";
    /**
     * <code>string phoneNumber = 2;</code>
     * @return The phoneNumber.
     */
    @java.lang.Override
    public java.lang.String getPhoneNumber() {
      java.lang.Object ref = phoneNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phoneNumber_ = s;
        return s;
      }
    }
    /**
     * <code>string phoneNumber = 2;</code>
     * @return The bytes for phoneNumber.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPhoneNumberBytes() {
      java.lang.Object ref = phoneNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phoneNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object email_ = "";
    /**
     * <code>string email = 3;</code>
     * @return The email.
     */
    @java.lang.Override
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 3;</code>
     * @return The bytes for email.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(phoneNumber_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, phoneNumber_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(email_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, email_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(phoneNumber_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, phoneNumber_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(email_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, email_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof utils.protobuf.ContactBookProto.Contact)) {
        return super.equals(obj);
      }
      utils.protobuf.ContactBookProto.Contact other = (utils.protobuf.ContactBookProto.Contact) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getPhoneNumber()
          .equals(other.getPhoneNumber())) return false;
      if (!getEmail()
          .equals(other.getEmail())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + PHONENUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getPhoneNumber().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static utils.protobuf.ContactBookProto.Contact parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static utils.protobuf.ContactBookProto.Contact parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static utils.protobuf.ContactBookProto.Contact parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static utils.protobuf.ContactBookProto.Contact parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static utils.protobuf.ContactBookProto.Contact parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static utils.protobuf.ContactBookProto.Contact parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static utils.protobuf.ContactBookProto.Contact parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static utils.protobuf.ContactBookProto.Contact parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static utils.protobuf.ContactBookProto.Contact parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static utils.protobuf.ContactBookProto.Contact parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static utils.protobuf.ContactBookProto.Contact parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static utils.protobuf.ContactBookProto.Contact parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(utils.protobuf.ContactBookProto.Contact prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Contact}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Contact)
        utils.protobuf.ContactBookProto.ContactOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return utils.protobuf.ContactBookProto.internal_static_Contact_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return utils.protobuf.ContactBookProto.internal_static_Contact_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                utils.protobuf.ContactBookProto.Contact.class, utils.protobuf.ContactBookProto.Contact.Builder.class);
      }

      // Construct using utils.protobuf.ContactBookProto.Contact.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        name_ = "";
        phoneNumber_ = "";
        email_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return utils.protobuf.ContactBookProto.internal_static_Contact_descriptor;
      }

      @java.lang.Override
      public utils.protobuf.ContactBookProto.Contact getDefaultInstanceForType() {
        return utils.protobuf.ContactBookProto.Contact.getDefaultInstance();
      }

      @java.lang.Override
      public utils.protobuf.ContactBookProto.Contact build() {
        utils.protobuf.ContactBookProto.Contact result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public utils.protobuf.ContactBookProto.Contact buildPartial() {
        utils.protobuf.ContactBookProto.Contact result = new utils.protobuf.ContactBookProto.Contact(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(utils.protobuf.ContactBookProto.Contact result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.phoneNumber_ = phoneNumber_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.email_ = email_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof utils.protobuf.ContactBookProto.Contact) {
          return mergeFrom((utils.protobuf.ContactBookProto.Contact)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(utils.protobuf.ContactBookProto.Contact other) {
        if (other == utils.protobuf.ContactBookProto.Contact.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getPhoneNumber().isEmpty()) {
          phoneNumber_ = other.phoneNumber_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                phoneNumber_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                email_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object phoneNumber_ = "";
      /**
       * <code>string phoneNumber = 2;</code>
       * @return The phoneNumber.
       */
      public java.lang.String getPhoneNumber() {
        java.lang.Object ref = phoneNumber_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          phoneNumber_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string phoneNumber = 2;</code>
       * @return The bytes for phoneNumber.
       */
      public com.google.protobuf.ByteString
          getPhoneNumberBytes() {
        java.lang.Object ref = phoneNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phoneNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string phoneNumber = 2;</code>
       * @param value The phoneNumber to set.
       * @return This builder for chaining.
       */
      public Builder setPhoneNumber(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        phoneNumber_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string phoneNumber = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPhoneNumber() {
        phoneNumber_ = getDefaultInstance().getPhoneNumber();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string phoneNumber = 2;</code>
       * @param value The bytes for phoneNumber to set.
       * @return This builder for chaining.
       */
      public Builder setPhoneNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        phoneNumber_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 3;</code>
       * @return The email.
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 3;</code>
       * @return The bytes for email.
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 3;</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        email_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        email_ = getDefaultInstance().getEmail();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        email_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Contact)
    }

    // @@protoc_insertion_point(class_scope:Contact)
    private static final utils.protobuf.ContactBookProto.Contact DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new utils.protobuf.ContactBookProto.Contact();
    }

    public static utils.protobuf.ContactBookProto.Contact getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Contact>
        PARSER = new com.google.protobuf.AbstractParser<Contact>() {
      @java.lang.Override
      public Contact parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Contact> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Contact> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public utils.protobuf.ContactBookProto.Contact getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ContactBookOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ContactBook)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Contact contactLists = 1;</code>
     */
    java.util.List<utils.protobuf.ContactBookProto.Contact> 
        getContactListsList();
    /**
     * <code>repeated .Contact contactLists = 1;</code>
     */
    utils.protobuf.ContactBookProto.Contact getContactLists(int index);
    /**
     * <code>repeated .Contact contactLists = 1;</code>
     */
    int getContactListsCount();
    /**
     * <code>repeated .Contact contactLists = 1;</code>
     */
    java.util.List<? extends utils.protobuf.ContactBookProto.ContactOrBuilder> 
        getContactListsOrBuilderList();
    /**
     * <code>repeated .Contact contactLists = 1;</code>
     */
    utils.protobuf.ContactBookProto.ContactOrBuilder getContactListsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ContactBook}
   */
  public static final class ContactBook extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ContactBook)
      ContactBookOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 0,
        /* suffix= */ "",
        ContactBook.class.getName());
    }
    // Use ContactBook.newBuilder() to construct.
    private ContactBook(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ContactBook() {
      contactLists_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return utils.protobuf.ContactBookProto.internal_static_ContactBook_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return utils.protobuf.ContactBookProto.internal_static_ContactBook_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              utils.protobuf.ContactBookProto.ContactBook.class, utils.protobuf.ContactBookProto.ContactBook.Builder.class);
    }

    public static final int CONTACTLISTS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<utils.protobuf.ContactBookProto.Contact> contactLists_;
    /**
     * <code>repeated .Contact contactLists = 1;</code>
     */
    @java.lang.Override
    public java.util.List<utils.protobuf.ContactBookProto.Contact> getContactListsList() {
      return contactLists_;
    }
    /**
     * <code>repeated .Contact contactLists = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends utils.protobuf.ContactBookProto.ContactOrBuilder> 
        getContactListsOrBuilderList() {
      return contactLists_;
    }
    /**
     * <code>repeated .Contact contactLists = 1;</code>
     */
    @java.lang.Override
    public int getContactListsCount() {
      return contactLists_.size();
    }
    /**
     * <code>repeated .Contact contactLists = 1;</code>
     */
    @java.lang.Override
    public utils.protobuf.ContactBookProto.Contact getContactLists(int index) {
      return contactLists_.get(index);
    }
    /**
     * <code>repeated .Contact contactLists = 1;</code>
     */
    @java.lang.Override
    public utils.protobuf.ContactBookProto.ContactOrBuilder getContactListsOrBuilder(
        int index) {
      return contactLists_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < contactLists_.size(); i++) {
        output.writeMessage(1, contactLists_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < contactLists_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, contactLists_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof utils.protobuf.ContactBookProto.ContactBook)) {
        return super.equals(obj);
      }
      utils.protobuf.ContactBookProto.ContactBook other = (utils.protobuf.ContactBookProto.ContactBook) obj;

      if (!getContactListsList()
          .equals(other.getContactListsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getContactListsCount() > 0) {
        hash = (37 * hash) + CONTACTLISTS_FIELD_NUMBER;
        hash = (53 * hash) + getContactListsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static utils.protobuf.ContactBookProto.ContactBook parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static utils.protobuf.ContactBookProto.ContactBook parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static utils.protobuf.ContactBookProto.ContactBook parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static utils.protobuf.ContactBookProto.ContactBook parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static utils.protobuf.ContactBookProto.ContactBook parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static utils.protobuf.ContactBookProto.ContactBook parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static utils.protobuf.ContactBookProto.ContactBook parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static utils.protobuf.ContactBookProto.ContactBook parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static utils.protobuf.ContactBookProto.ContactBook parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static utils.protobuf.ContactBookProto.ContactBook parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static utils.protobuf.ContactBookProto.ContactBook parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static utils.protobuf.ContactBookProto.ContactBook parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(utils.protobuf.ContactBookProto.ContactBook prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ContactBook}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ContactBook)
        utils.protobuf.ContactBookProto.ContactBookOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return utils.protobuf.ContactBookProto.internal_static_ContactBook_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return utils.protobuf.ContactBookProto.internal_static_ContactBook_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                utils.protobuf.ContactBookProto.ContactBook.class, utils.protobuf.ContactBookProto.ContactBook.Builder.class);
      }

      // Construct using utils.protobuf.ContactBookProto.ContactBook.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (contactListsBuilder_ == null) {
          contactLists_ = java.util.Collections.emptyList();
        } else {
          contactLists_ = null;
          contactListsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return utils.protobuf.ContactBookProto.internal_static_ContactBook_descriptor;
      }

      @java.lang.Override
      public utils.protobuf.ContactBookProto.ContactBook getDefaultInstanceForType() {
        return utils.protobuf.ContactBookProto.ContactBook.getDefaultInstance();
      }

      @java.lang.Override
      public utils.protobuf.ContactBookProto.ContactBook build() {
        utils.protobuf.ContactBookProto.ContactBook result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public utils.protobuf.ContactBookProto.ContactBook buildPartial() {
        utils.protobuf.ContactBookProto.ContactBook result = new utils.protobuf.ContactBookProto.ContactBook(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(utils.protobuf.ContactBookProto.ContactBook result) {
        if (contactListsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            contactLists_ = java.util.Collections.unmodifiableList(contactLists_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.contactLists_ = contactLists_;
        } else {
          result.contactLists_ = contactListsBuilder_.build();
        }
      }

      private void buildPartial0(utils.protobuf.ContactBookProto.ContactBook result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof utils.protobuf.ContactBookProto.ContactBook) {
          return mergeFrom((utils.protobuf.ContactBookProto.ContactBook)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(utils.protobuf.ContactBookProto.ContactBook other) {
        if (other == utils.protobuf.ContactBookProto.ContactBook.getDefaultInstance()) return this;
        if (contactListsBuilder_ == null) {
          if (!other.contactLists_.isEmpty()) {
            if (contactLists_.isEmpty()) {
              contactLists_ = other.contactLists_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureContactListsIsMutable();
              contactLists_.addAll(other.contactLists_);
            }
            onChanged();
          }
        } else {
          if (!other.contactLists_.isEmpty()) {
            if (contactListsBuilder_.isEmpty()) {
              contactListsBuilder_.dispose();
              contactListsBuilder_ = null;
              contactLists_ = other.contactLists_;
              bitField0_ = (bitField0_ & ~0x00000001);
              contactListsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getContactListsFieldBuilder() : null;
            } else {
              contactListsBuilder_.addAllMessages(other.contactLists_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                utils.protobuf.ContactBookProto.Contact m =
                    input.readMessage(
                        utils.protobuf.ContactBookProto.Contact.parser(),
                        extensionRegistry);
                if (contactListsBuilder_ == null) {
                  ensureContactListsIsMutable();
                  contactLists_.add(m);
                } else {
                  contactListsBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<utils.protobuf.ContactBookProto.Contact> contactLists_ =
        java.util.Collections.emptyList();
      private void ensureContactListsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          contactLists_ = new java.util.ArrayList<utils.protobuf.ContactBookProto.Contact>(contactLists_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          utils.protobuf.ContactBookProto.Contact, utils.protobuf.ContactBookProto.Contact.Builder, utils.protobuf.ContactBookProto.ContactOrBuilder> contactListsBuilder_;

      /**
       * <code>repeated .Contact contactLists = 1;</code>
       */
      public java.util.List<utils.protobuf.ContactBookProto.Contact> getContactListsList() {
        if (contactListsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(contactLists_);
        } else {
          return contactListsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Contact contactLists = 1;</code>
       */
      public int getContactListsCount() {
        if (contactListsBuilder_ == null) {
          return contactLists_.size();
        } else {
          return contactListsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Contact contactLists = 1;</code>
       */
      public utils.protobuf.ContactBookProto.Contact getContactLists(int index) {
        if (contactListsBuilder_ == null) {
          return contactLists_.get(index);
        } else {
          return contactListsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Contact contactLists = 1;</code>
       */
      public Builder setContactLists(
          int index, utils.protobuf.ContactBookProto.Contact value) {
        if (contactListsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContactListsIsMutable();
          contactLists_.set(index, value);
          onChanged();
        } else {
          contactListsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Contact contactLists = 1;</code>
       */
      public Builder setContactLists(
          int index, utils.protobuf.ContactBookProto.Contact.Builder builderForValue) {
        if (contactListsBuilder_ == null) {
          ensureContactListsIsMutable();
          contactLists_.set(index, builderForValue.build());
          onChanged();
        } else {
          contactListsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Contact contactLists = 1;</code>
       */
      public Builder addContactLists(utils.protobuf.ContactBookProto.Contact value) {
        if (contactListsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContactListsIsMutable();
          contactLists_.add(value);
          onChanged();
        } else {
          contactListsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Contact contactLists = 1;</code>
       */
      public Builder addContactLists(
          int index, utils.protobuf.ContactBookProto.Contact value) {
        if (contactListsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContactListsIsMutable();
          contactLists_.add(index, value);
          onChanged();
        } else {
          contactListsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Contact contactLists = 1;</code>
       */
      public Builder addContactLists(
          utils.protobuf.ContactBookProto.Contact.Builder builderForValue) {
        if (contactListsBuilder_ == null) {
          ensureContactListsIsMutable();
          contactLists_.add(builderForValue.build());
          onChanged();
        } else {
          contactListsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Contact contactLists = 1;</code>
       */
      public Builder addContactLists(
          int index, utils.protobuf.ContactBookProto.Contact.Builder builderForValue) {
        if (contactListsBuilder_ == null) {
          ensureContactListsIsMutable();
          contactLists_.add(index, builderForValue.build());
          onChanged();
        } else {
          contactListsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Contact contactLists = 1;</code>
       */
      public Builder addAllContactLists(
          java.lang.Iterable<? extends utils.protobuf.ContactBookProto.Contact> values) {
        if (contactListsBuilder_ == null) {
          ensureContactListsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, contactLists_);
          onChanged();
        } else {
          contactListsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Contact contactLists = 1;</code>
       */
      public Builder clearContactLists() {
        if (contactListsBuilder_ == null) {
          contactLists_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          contactListsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Contact contactLists = 1;</code>
       */
      public Builder removeContactLists(int index) {
        if (contactListsBuilder_ == null) {
          ensureContactListsIsMutable();
          contactLists_.remove(index);
          onChanged();
        } else {
          contactListsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Contact contactLists = 1;</code>
       */
      public utils.protobuf.ContactBookProto.Contact.Builder getContactListsBuilder(
          int index) {
        return getContactListsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Contact contactLists = 1;</code>
       */
      public utils.protobuf.ContactBookProto.ContactOrBuilder getContactListsOrBuilder(
          int index) {
        if (contactListsBuilder_ == null) {
          return contactLists_.get(index);  } else {
          return contactListsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Contact contactLists = 1;</code>
       */
      public java.util.List<? extends utils.protobuf.ContactBookProto.ContactOrBuilder> 
           getContactListsOrBuilderList() {
        if (contactListsBuilder_ != null) {
          return contactListsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(contactLists_);
        }
      }
      /**
       * <code>repeated .Contact contactLists = 1;</code>
       */
      public utils.protobuf.ContactBookProto.Contact.Builder addContactListsBuilder() {
        return getContactListsFieldBuilder().addBuilder(
            utils.protobuf.ContactBookProto.Contact.getDefaultInstance());
      }
      /**
       * <code>repeated .Contact contactLists = 1;</code>
       */
      public utils.protobuf.ContactBookProto.Contact.Builder addContactListsBuilder(
          int index) {
        return getContactListsFieldBuilder().addBuilder(
            index, utils.protobuf.ContactBookProto.Contact.getDefaultInstance());
      }
      /**
       * <code>repeated .Contact contactLists = 1;</code>
       */
      public java.util.List<utils.protobuf.ContactBookProto.Contact.Builder> 
           getContactListsBuilderList() {
        return getContactListsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          utils.protobuf.ContactBookProto.Contact, utils.protobuf.ContactBookProto.Contact.Builder, utils.protobuf.ContactBookProto.ContactOrBuilder> 
          getContactListsFieldBuilder() {
        if (contactListsBuilder_ == null) {
          contactListsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              utils.protobuf.ContactBookProto.Contact, utils.protobuf.ContactBookProto.Contact.Builder, utils.protobuf.ContactBookProto.ContactOrBuilder>(
                  contactLists_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          contactLists_ = null;
        }
        return contactListsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ContactBook)
    }

    // @@protoc_insertion_point(class_scope:ContactBook)
    private static final utils.protobuf.ContactBookProto.ContactBook DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new utils.protobuf.ContactBookProto.ContactBook();
    }

    public static utils.protobuf.ContactBookProto.ContactBook getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ContactBook>
        PARSER = new com.google.protobuf.AbstractParser<ContactBook>() {
      @java.lang.Override
      public ContactBook parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ContactBook> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ContactBook> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public utils.protobuf.ContactBookProto.ContactBook getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Contact_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Contact_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ContactBook_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ContactBook_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021Contactbook.proto\";\n\007Contact\022\014\n\004name\030\001" +
      " \001(\t\022\023\n\013phoneNumber\030\002 \001(\t\022\r\n\005email\030\003 \001(\t" +
      "\"-\n\013ContactBook\022\036\n\014contactLists\030\001 \003(\0132\010." +
      "ContactB\"\n\016utils.protobufB\020ContactBookPr" +
      "otob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Contact_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Contact_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Contact_descriptor,
        new java.lang.String[] { "Name", "PhoneNumber", "Email", });
    internal_static_ContactBook_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ContactBook_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ContactBook_descriptor,
        new java.lang.String[] { "ContactLists", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
